webapp/project/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    email = StringField('Email', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])


class RegisterForm(FlaskForm):
    email = StringField(
        'Email Address',
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40)
        ]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Los passworLos passwords deben ser identicos')
        ]
    )

webapp/project/server/user/__init__.py
# project/server/user/__init__.py

webapp/project/server/user/views.py
# project/server/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from project.server import bcrypt, db
from project.server.models import User
from project.server.user.forms import LoginForm, RegisterForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,
        url_prefix="/conectividad",
        static_folder='../../client/static'
        )


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Gracias por suscribirte', 'success')
        return redirect(url_for("main.home"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Bienvenido', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Password o usuario incorrectos', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Has entrado al sistema', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

webapp/project/client/templates/user/login.html
{% extends '_base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}

  <div class="content">
  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}


	{{ render_field(form.email,'envelope',"Escribe tu correo") }}
	{{ render_field(form.password,'lock',"Escribe tu password") }}

	<div class="field is-grouped">
	  <div class="control">
		<button class="button is-primary" type="submit">Entrar</button>
	  </div>
	  <div class="control">
		<button class="button is-link"><a href="{{url_for('main.home')}}">Cancelar</a></button>
	  </div>
	</div>

      <p>¿Todavía no estás regisrado? <a href="{{ url_for('user.register') }}">Registrarse</a></p>
    </div>

  </form>
  </div>


{% endblock content %}

webapp/project/client/templates/user/members.html
{% extends "_base.html" %}
{% block content %}
  <h1>Welcome, <em>{{ current_user.email }}</em>!</h1>
  <h3>This is the members-only page.</h3>
{% endblock %}

webapp/project/client/templates/user/register.html
{% extends '_base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}

  <div class="content">
    <h3 class="title">Datos de registro</h3>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}

	{{ render_field(form.email,'envelope',"Escribe tu correo") }}
	{{ render_field(form.password,'lock',"Escribe tu password") }}
	{{ render_field(form.password,'refresh',"Reescribe tu password") }}


	<div class="field is-grouped">
	  <div class="control">
		<button class="button is-primary" type="submit">Registrarse</button>
	  </div>
	  <div class="control">
		<button class="button is-link"><a href="{{url_for('main.home')}}">Cancelar</></button>
	  </div>
	</div>
    </div>

  </form>
  </div>



{% endblock content %}