webapp/project/server/main/views.py
# project/server/main/views.py


#################
#### imports ####
#################
import matplotlib
matplotlib.use('Agg')
from flask import render_template, Blueprint, send_from_directory, request
from flask import jsonify, url_for
from datetime import datetime
from collections import Counter

import os.path
import os

import nltk
#from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import wordpunct_tokenize
from nltk.probability import FreqDist
import networkx as nx
from py2neo import Graph
import operator

#######################
#### loading JSONDB ###
#######################

from tinydb import TinyDB, Query
db = TinyDB('DB.json')
contensiosos = db.table('contensiosos')
CaseQ = Query()


#######################
#### loading JSONGRPAH ###
#######################
import json
with open('graph.json') as data_file:
    json_graph = json.load(data_file)


#######################
#### loading GRPAH ###
#######################
from project.server.main import config
graph__ = Graph("bolt://127.0.0.1:7687", auth=(config.NEO4J_USER, config.NEO4J_PASSWORD))


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,
    url_prefix="/conectividad",
    static_folder='../../client/static'
    )


api_blueprint = Blueprint('api', __name__,
    url_prefix="/conectividad/api",
    static_folder='../../client/static'
    )



import re

################
#### forms ####
################
from wtforms import IntegerField, StringField, BooleanField, Form
from wtforms.validators import DataRequired


class GraphForm(Form):
    include = StringField('include')
    exclude = StringField('exclude')
    include_doc = StringField('include_doc')
    exclude_doc = StringField('exclude_doc')
    court_cases = BooleanField()
    min = IntegerField()
    arts = BooleanField()

################
#### routes ####
################

name_country={
"argentina":"Argentina",
"barbados":"Barbados",
"bolivia":"Bolivia",
"brasil":"Brasil",
"chile":"Chile",
"colombia":"Colombia",
"costa rica":"Costa Rica",
"dominicana":"Dominicana",
"ecuador":"Ecuador",
"el salvador":"El Salvador",
"guatemala":"Guatemala",
"granada":"Granada",
"haití":"Haití",
"honduras":"Honduras",
"jamaica":"Jamaica",
"méxico":"México",
"nicaragua":"Nicaragua",
"panamá":"Panama",
"paraguay":"Paraguay",
"perú":"Perú",
"república dominicana":"República Dominicana",
"trinidad y tobago":"Trinidad y Tobago",
"surinam":"Surinam",
"uruguay":"Uruguay",
"venezuela":"Venezuela",
}



color_country={
"argentina":"#922b21",
"barbados":"#cb4335",
"bolivia":"#884ea0",
"brasil":"#7d3c98",
"chile":"#2471a3",
"colombia":"#2e86c1",
"costa rica":"#2e86c1",
"dominicana":"#17a589",
"ecuador":"#138d75",
"el salvador":"#f1c40f",
"guatemala":"#d68910",
"granada":"#d68910",
"haití":"#800000",
"honduras":"#008080",
"jamaica":"#ffff00",
"méxico":"#008000",
"nicaragua":"#0000ff",
"panama":"#000080",
"paraguay":"#800080",
"perú":"#ff0000",
"república dominicana":"#ff5733",
"trinidad y tobago":"#808000",
"surinam":"#ffce00",
"uruguay":"#5ac8d8",
"venezuela":"#cf0a2c",
}

common_documents=[
 "comisión interamericana de derechos humanos",
 "convención interamericana de derechos humanos",
 "convención americana sobre derechos humanos",
 "reglamento de la corte",
]

@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

@main_blueprint.route("/laws/")
def laws():
    return render_template("main/laws.html",docs=contensiosos.all())

@main_blueprint.route("/law/<int:idd>")
def law(idd):
    return render_template("main/law.html",doc=contensiosos.get(eid=idd))


@main_blueprint.route("/doc/", methods=["GET","POST"])
def doc():
    # Para GET
    xmlName = request.args.get('docXmlName')
    docNum = request.args.get('docNum')
    # Para POST , no funciona actualmente :(
    #xmlName = request.args['docXmlName']
    #docNum = request.args['docNum']
    docNum = eval(docNum)

    stop_words = set(stopwords.words('spanish'))
    stop_words.update(
        ['.', ',', '“', "”", '"', "'", '¿', '?', '!', '¡', ':', ';', '(', ')', '°',
        ".(", ").","(”", "”)", "”),", "”).", "),", '[', ']', "[.", ".]", '{', '}',
        "”.", "].", "[.]", '_','-','/', "_________________________"]
    )

    with open('contenciosos/text/'+xmlName) as filename:
        lines=filename.readlines()

    cleaned = ""
    for line in lines:
        cleaned += line + " "

    cleanLines = [i.lower() for i in wordpunct_tokenize(cleaned) if i.lower() not in stop_words]

    fdist = FreqDist(cleanLines)


    with open('labelledDocuments/'+xmlName+".xml") as filename:
        lines=filename.readlines()
        lines=[line.replace("\n",'') for line in lines]



    return render_template("main/documents.html",filename=xmlName+".xml", xml=lines,
        doc=contensiosos.get(eid=docNum),fdist=fdist,nwords=20,nvoc=100)


@main_blueprint.route("/xml/<string:filename>")
def xml(filename):
    gate_css_url=url_for('main.static', filename='gate.css')
    gate_js_url=url_for('main.static', filename='gate.js')
    string="""
<!DOCTYPE html>
<html xml:lang="en" lang="en">
    <head>
        <base>
            <title>Conectividad Normativa</title>
            <link href="{0}" rel="stylesheet" media="screen"></link>
        </base>
    </head>
    <body>
        {2}
        <script src="{1}" type="text/javascript"></script>
    </body>
</html>
"""
    with open('labelledDocuments/'+filename) as filename:
        lines=filename.readlines()

    return string.format(gate_css_url,gate_js_url,"<br/>".join(lines))

@main_blueprint.route("/graph/",methods=["GET","POST"])
def graph():
    form = GraphForm(request.form)
    if request.method == 'POST' and form.validate():
        query={}
        if form.include.data:
            query["include"]=form.include.data
        if form.exclude.data:
            query["exclude"]=form.exclude.data
        if form.include_doc.data:
            query["include_doc"]=form.include_doc.data
        if form.exclude_doc.data:
            query["exclude_doc"]=form.exclude_doc.data
        if form.min.data:
            query["min"]=int(form.min.data)
        if form.arts.data:
            query["exp_arts"]="true"
        if form.court_cases.data:
            query["court_cases"]="true"
        if len(query)>0:
            return render_template("main/graph.html",params=query,year=datetime.now().year)
        else:
            return render_template("main/graph.html",params={},year=datetime.now().year)
    return render_template("main/graph_selection.html",form=form,common_documents="({})".format("|".join(common_documents)))

@main_blueprint.route("/numbers/")
def numbers():
    return render_template("main/list_numbers.html")

@main_blueprint.route("/numbers/cases_country")
def cases_country():
    country_cases= Counter()

    countries=[]
    for node in json_graph['nodes']:
        if node['type']==1:
            countries.append(node['country'])
    country_cases=Counter(countries)

    return render_template("main/cases_country.html",
			data=country_cases,
			color_country=color_country,
			name_country=name_country,
			total_cases=sum(country_cases.values()))


@main_blueprint.route("/numbers/articles_citation/<int:ntop>")
@main_blueprint.route("/numbers/articles_citation")
def articles_citation(ntop=200):
    country_cases= Counter()

    articles=[]
    for node in json_graph['nodes']:
        if node['type']==3:
            articles.append((node['id'],(node['doc'],node['art'])))
    articles=dict(articles)

    articles_citation=Counter()
    for link in json_graph['links']:
        if  link['target'] in articles:
            try:
                articles_citation[articles[link["target"]]]+=int(link['ori_val'])
            except KeyError:
                articles_citation[articles[link["target"]]]=int(link['ori_val'])


    return render_template("main/articles_citation.html",
			data=articles_citation,
			total_articles=sum(articles_citation.values()),ntop=ntop)


@main_blueprint.route("/numbers/density_country")
@main_blueprint.route("/numbers/density_country/<int:min_value>")
def numbers_density_country(min_value=5):
    countries={}
    for country in name_country.keys():
        G = nx.DiGraph()
        nodes_=set()
        edges_=[]
        targets_=set()
        for node in json_graph['nodes']:
            if node['type']==1 and node['country']==country:
                nodes_.add(node['id'])
            if node['type']==2:
                targets_.add(node['id'])
        for link in json_graph['links']:
            if link['source'] in nodes_ and link['target'] in targets_ and link['ori_val']>=min_value:
                nodes_.add(node['id'])
                edges_.append((link['source'],link['target'],link['ori_val']))

        G.add_nodes_from(nodes_ )
        G.add_weighted_edges_from([ e for e in edges_ ])
        d=nx.density(G)
        countries[country]=d

    return render_template("main/country.html",
                        title="Densidad grafo por país",
			data=countries,
                        country_names=[x for x,y in sorted(countries.items(), key=operator.itemgetter(1),reverse=True)],
			color_country=color_country,
			name_country=name_country)


@main_blueprint.route("/numbers/adc_country")
@main_blueprint.route("/numbers/adc_country/<int:min_value>")
def numbers_adc_country(min_value=5):
    countries={}
    for country in name_country.keys():
        G = nx.DiGraph()
        nodes_=set()
        edges_=[]
        targets_=set()
        for node in json_graph['nodes']:
            if node['type']==1 and node['country']==country:
                nodes_.add(node['id'])
            if node['type']==2:
                targets_.add(node['id'])
        for link in json_graph['links']:
            if link['source'] in nodes_ and link['target'] in targets_ and link['ori_val']>=min_value:

webapp/project/server/user/views.py
# project/server/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from project.server import bcrypt, db
from project.server.models import User
from project.server.user.forms import LoginForm, RegisterForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,
        url_prefix="/conectividad",
        static_folder='../../client/static'
        )


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Gracias por suscribirte', 'success')
        return redirect(url_for("main.home"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Bienvenido', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Password o usuario incorrectos', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Has entrado al sistema', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

webapp/project/client/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <base href="/conectividad/">
    <meta charset="utf-8">
    <title>Conectividad Normativa{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Force to reload -->
    <meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0" />
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />

    <!-- styles -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <link href="{{url_for('main.static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>
        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-9640902-7', 'auto');
      ga('send', 'pageview');

    </script>
    <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="{{url_for('main.static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

webapp/project/client/templates/_formhelpers.html
{% macro render_field(field,icon,placeholder) %}
	<div class="field">
	  <p class="control has-icons-left has-icons-right">
  		{{ field(class_="input",placeholder=placeholder,**kwargs)|safe }}
		<span class="icon is-small is-left">
		  <i class="fas fa-{{icon}}"></i>
		</span>
	  </p>
	</div>


  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

webapp/project/client/templates/footer.html
<footer class="footer is-info">
  <div class="container">
    <div class="content has-text-centered">
      <hr/>
  		<p>
  			Sitio versión 0.1.0 </br>
  			Constructivismo jurídico complejo: cognición, complejidad y derecho<br/>
  			CONACYT Fronteras de la Ciencia (NUMERO)
  		</p>
  		<p>
    		Instituciones participantes:
    		<a href="https://www.juridicas.unam.mx">IIJ</a>,
    		<a href="https://www.iimas.unam.mx">IIMAS</a>,
    		<a href="https://www.unam.mx/">UNAM</a>,
    		<a href="https://www.conacyt.mx">CONACYT</a>,
  		</p>
      <p>
        <img src="{{url_for('main.static', filename='footer_institutions_small.png')}}" alt="Instituciones participantes"/>
      </p>
    </div>
  </div>
</footer>

webapp/project/client/templates/header.html
  <!-- Navigation -->
<header>
  <nav class="navbar ">
    <div id="navMainMenu" class="navbar-menu">
  	  <div class="navbar-start">
    	  <a class="navbar-item " href="{{ url_for('main.home') }}">
          <span class="icon">
    	       <i class="fa fa-2x fa-home"></i>
    		  </span>
        </a>

        <a class="navbar-item " href="{{ url_for('main.laws') }}">
          Sentencias
        </a>

      	<a class="navbar-item " href="{{ url_for('main.numbers') }}">
          Números
        </a>

        <a class="navbar-item " href="{{ url_for('main.graph') }}">
          Conectividad
        </a>

        <a class="navbar-item " href="{{ url_for('main.about') }}">
          Acerca
        </a>
  	  </div>


  	  <div class="navbar-end">
        {% if current_user.is_authenticated %}
        <a class="navbar-item " href="{{ url_for('main.members') }}">
          Miembros
        </a>
        {% endif %}
        {% if current_user.is_authenticated %}
        <a class="navbar-item " href="{{ url_for('user.logout') }}">
          <span class="icon" style="color: #333;">
            <i class="fas fa-sign-out-alt"></i>
          </span>Salir
        </a>

        {% else %}
        <a class="navbar-item " href="{{ url_for('user.login') }}">
          <span class="icon" style="color: #333;">
            <i class="fas fa-sign-in-alt"></i>
          </span> Entrar/Registrarse
  	     </a>
         {% endif %}
       </div>
     </div>
  </nav>

  <section class="hero is-primary">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
             <strong>Conectividad Normativa</strong>
        </h1>
        <h2 class="subtitle">
          Visualizador de conectividad de las sentencias de la Corte Interamericana de Derechos Humanos
        </h2>
      </div>
    </div>
  </section>
</header>