webapp/project/server/main/__init__.py
# project/server/main/__init__.py

webapp/project/server/main/views.py
# project/server/main/views.py


#################
#### imports ####
#################
import matplotlib
matplotlib.use('Agg')
from flask import render_template, Blueprint, send_from_directory, request
from flask import jsonify, url_for
from datetime import datetime
from collections import Counter

import os.path
import os

import nltk
#from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import wordpunct_tokenize
from nltk.probability import FreqDist
import networkx as nx
from py2neo import Graph
import operator

#######################
#### loading JSONDB ###
#######################

from tinydb import TinyDB, Query
db = TinyDB('DB.json')
contensiosos = db.table('contensiosos')
CaseQ = Query()


#######################
#### loading JSONGRPAH ###
#######################
import json
with open('graph.json') as data_file:
    json_graph = json.load(data_file)


#######################
#### loading GRPAH ###
#######################
from project.server.main import config
graph__ = Graph("bolt://127.0.0.1:7687", auth=(config.NEO4J_USER, config.NEO4J_PASSWORD))


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,
    url_prefix="/conectividad",
    static_folder='../../client/static'
    )


api_blueprint = Blueprint('api', __name__,
    url_prefix="/conectividad/api",
    static_folder='../../client/static'
    )



import re

################
#### forms ####
################
from wtforms import IntegerField, StringField, BooleanField, Form
from wtforms.validators import DataRequired


class GraphForm(Form):
    include = StringField('include')
    exclude = StringField('exclude')
    include_doc = StringField('include_doc')
    exclude_doc = StringField('exclude_doc')
    court_cases = BooleanField()
    min = IntegerField()
    arts = BooleanField()

################
#### routes ####
################

name_country={
"argentina":"Argentina",
"barbados":"Barbados",
"bolivia":"Bolivia",
"brasil":"Brasil",
"chile":"Chile",
"colombia":"Colombia",
"costa rica":"Costa Rica",
"dominicana":"Dominicana",
"ecuador":"Ecuador",
"el salvador":"El Salvador",
"guatemala":"Guatemala",
"granada":"Granada",
"haití":"Haití",
"honduras":"Honduras",
"jamaica":"Jamaica",
"méxico":"México",
"nicaragua":"Nicaragua",
"panamá":"Panama",
"paraguay":"Paraguay",
"perú":"Perú",
"república dominicana":"República Dominicana",
"trinidad y tobago":"Trinidad y Tobago",
"surinam":"Surinam",
"uruguay":"Uruguay",
"venezuela":"Venezuela",
}



color_country={
"argentina":"#922b21",
"barbados":"#cb4335",
"bolivia":"#884ea0",
"brasil":"#7d3c98",
"chile":"#2471a3",
"colombia":"#2e86c1",
"costa rica":"#2e86c1",
"dominicana":"#17a589",
"ecuador":"#138d75",
"el salvador":"#f1c40f",
"guatemala":"#d68910",
"granada":"#d68910",
"haití":"#800000",
"honduras":"#008080",
"jamaica":"#ffff00",
"méxico":"#008000",
"nicaragua":"#0000ff",
"panama":"#000080",
"paraguay":"#800080",
"perú":"#ff0000",
"república dominicana":"#ff5733",
"trinidad y tobago":"#808000",
"surinam":"#ffce00",
"uruguay":"#5ac8d8",
"venezuela":"#cf0a2c",
}

common_documents=[
 "comisión interamericana de derechos humanos",
 "convención interamericana de derechos humanos",
 "convención americana sobre derechos humanos",
 "reglamento de la corte",
]

@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

@main_blueprint.route("/laws/")
def laws():
    return render_template("main/laws.html",docs=contensiosos.all())

@main_blueprint.route("/law/<int:idd>")
def law(idd):
    return render_template("main/law.html",doc=contensiosos.get(eid=idd))


@main_blueprint.route("/doc/", methods=["GET","POST"])
def doc():
    # Para GET
    xmlName = request.args.get('docXmlName')
    docNum = request.args.get('docNum')
    # Para POST , no funciona actualmente :(
    #xmlName = request.args['docXmlName']
    #docNum = request.args['docNum']
    docNum = eval(docNum)

    stop_words = set(stopwords.words('spanish'))
    stop_words.update(
        ['.', ',', '“', "”", '"', "'", '¿', '?', '!', '¡', ':', ';', '(', ')', '°',
        ".(", ").","(”", "”)", "”),", "”).", "),", '[', ']', "[.", ".]", '{', '}',
        "”.", "].", "[.]", '_','-','/', "_________________________"]
    )

    with open('contenciosos/text/'+xmlName) as filename:
        lines=filename.readlines()

    cleaned = ""
    for line in lines:
        cleaned += line + " "

    cleanLines = [i.lower() for i in wordpunct_tokenize(cleaned) if i.lower() not in stop_words]

    fdist = FreqDist(cleanLines)


    with open('labelledDocuments/'+xmlName+".xml") as filename:
        lines=filename.readlines()
        lines=[line.replace("\n",'') for line in lines]



    return render_template("main/documents.html",filename=xmlName+".xml", xml=lines,
        doc=contensiosos.get(eid=docNum),fdist=fdist,nwords=20,nvoc=100)


@main_blueprint.route("/xml/<string:filename>")
def xml(filename):
    gate_css_url=url_for('main.static', filename='gate.css')
    gate_js_url=url_for('main.static', filename='gate.js')
    string="""
<!DOCTYPE html>
<html xml:lang="en" lang="en">
    <head>
        <base>
            <title>Conectividad Normativa</title>
            <link href="{0}" rel="stylesheet" media="screen"></link>
        </base>
    </head>
    <body>
        {2}
        <script src="{1}" type="text/javascript"></script>
    </body>
</html>
"""
    with open('labelledDocuments/'+filename) as filename:
        lines=filename.readlines()

    return string.format(gate_css_url,gate_js_url,"<br/>".join(lines))

@main_blueprint.route("/graph/",methods=["GET","POST"])
def graph():
    form = GraphForm(request.form)
    if request.method == 'POST' and form.validate():
        query={}
        if form.include.data:
            query["include"]=form.include.data
        if form.exclude.data:
            query["exclude"]=form.exclude.data
        if form.include_doc.data:
            query["include_doc"]=form.include_doc.data
        if form.exclude_doc.data:
            query["exclude_doc"]=form.exclude_doc.data
        if form.min.data:
            query["min"]=int(form.min.data)
        if form.arts.data:
            query["exp_arts"]="true"
        if form.court_cases.data:
            query["court_cases"]="true"
        if len(query)>0:
            return render_template("main/graph.html",params=query,year=datetime.now().year)
        else:
            return render_template("main/graph.html",params={},year=datetime.now().year)
    return render_template("main/graph_selection.html",form=form,common_documents="({})".format("|".join(common_documents)))

@main_blueprint.route("/numbers/")
def numbers():
    return render_template("main/list_numbers.html")

@main_blueprint.route("/numbers/cases_country")
def cases_country():
    country_cases= Counter()

    countries=[]
    for node in json_graph['nodes']:
        if node['type']==1:
            countries.append(node['country'])
    country_cases=Counter(countries)

    return render_template("main/cases_country.html",
			data=country_cases,
			color_country=color_country,
			name_country=name_country,
			total_cases=sum(country_cases.values()))


@main_blueprint.route("/numbers/articles_citation/<int:ntop>")
@main_blueprint.route("/numbers/articles_citation")
def articles_citation(ntop=200):
    country_cases= Counter()

    articles=[]
    for node in json_graph['nodes']:
        if node['type']==3:
            articles.append((node['id'],(node['doc'],node['art'])))
    articles=dict(articles)

    articles_citation=Counter()
    for link in json_graph['links']:
        if  link['target'] in articles:
            try:
                articles_citation[articles[link["target"]]]+=int(link['ori_val'])
            except KeyError:
                articles_citation[articles[link["target"]]]=int(link['ori_val'])


    return render_template("main/articles_citation.html",
			data=articles_citation,
			total_articles=sum(articles_citation.values()),ntop=ntop)


@main_blueprint.route("/numbers/density_country")
@main_blueprint.route("/numbers/density_country/<int:min_value>")
def numbers_density_country(min_value=5):
    countries={}
    for country in name_country.keys():
        G = nx.DiGraph()
        nodes_=set()
        edges_=[]
        targets_=set()
        for node in json_graph['nodes']:
            if node['type']==1 and node['country']==country:
                nodes_.add(node['id'])
            if node['type']==2:
                targets_.add(node['id'])
        for link in json_graph['links']:
            if link['source'] in nodes_ and link['target'] in targets_ and link['ori_val']>=min_value:
                nodes_.add(node['id'])
                edges_.append((link['source'],link['target'],link['ori_val']))

        G.add_nodes_from(nodes_ )
        G.add_weighted_edges_from([ e for e in edges_ ])
        d=nx.density(G)
        countries[country]=d

    return render_template("main/country.html",
                        title="Densidad grafo por país",
			data=countries,
                        country_names=[x for x,y in sorted(countries.items(), key=operator.itemgetter(1),reverse=True)],
			color_country=color_country,
			name_country=name_country)


@main_blueprint.route("/numbers/adc_country")
@main_blueprint.route("/numbers/adc_country/<int:min_value>")
def numbers_adc_country(min_value=5):
    countries={}
    for country in name_country.keys():
        G = nx.DiGraph()
        nodes_=set()
        edges_=[]
        targets_=set()
        for node in json_graph['nodes']:
            if node['type']==1 and node['country']==country:
                nodes_.add(node['id'])
            if node['type']==2:
                targets_.add(node['id'])
        for link in json_graph['links']:
            if link['source'] in nodes_ and link['target'] in targets_ and link['ori_val']>=min_value:

webapp/project/client/templates/main/about.html
{% extends "_base.html" %}

{% block content %}

<div class="content">
<p>
<h3 class="title">Publicaciones</h3>
<!--<ul>
	<li>Por venir</li>
</ul>-->
</p>


<p>
<h3 class="title">Participantes</h3>
<ul>
	<h4>Responsable Técnico del Proyecto</h4>
	<li>Dr. Enrique Cáceres, <a href="http://www.jurídicas.unam.mx">Instituto de Investigaciones Jurídicas</a></li>
	</br><h4>Investigadores participantes</h4>
	<li>Dra. Frida Díaz Barriga Arceo, <a href="http://www.psicologia.unam.mx/">Facultad de Psicología</a></li>
	<li>Dr. Adonis Germinal Cocho Gil, <a href="http://scifunam.fisica.unam.mx/index.php">Instituto de Física</a></li>
	<li>Dr. Fernando Castaños Zuno, <a href="http://www.iis.unam.mx/">Instituto de Investigaciones Sociales</a></li>
	<li>Dr. Ricardo Mansilla Corona, <a href="http://www.ceiich.unam.mx/0/index.php">Centro de Investigaciones Interdisciplinarias en Ciencias y Humanidades</a></li>
	<li>Professor Burkhard Schafer, <a href="http://www.ed.ac.uk">The University of Edinburgh</a></li>
	<li>Dr. Ivan Vladimir Meza Ruiz, <a href="http://www.iimas.unam.mx">Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas</a></li>
	<li>Dra. Margarita Palacios Sierra, <a href="http://www.filos.unam.mx/">Facultad de Filosofía y Letras</a></li>
	</br><h4>Estudiantes participantes</h4>
	<li>Mtra. Carmen Patricia López Olvera, <a href="http://www.jurídicas.unam.mx">Instituto de Investigaciones Jurídicas</a></li>
	<li>Lic. Giovanni Lizárraga Félix, <a href="http://www.jurídicas.unam.mx">Instituto de Investigaciones Jurídicas</a></li>
	<li>Lic. Raúl Gómez Toledo, <a href="http://www.jurídicas.unam.mx">Instituto de Investigaciones Jurídicas</a></li>
	<li>Lic. Daniel Atilano, <a href="http://www.jurídicas.unam.mx">Instituto de Investigaciones Jurídicas</a></li>
	<li>Ing. Paul Sebastian Aguilar Enriquez, <a href="http://www.ingenieria.unam.mx/">Facultad de Ingeniería</a></li>
</ul>

</p>
</div>



{% endblock %}

webapp/project/client/templates/main/articles_citation.html
{% extends "_base.html" %}

{% block content %}
<div class="content">

{% if ntop %}
<h3>{{ntop }} Artículos citados</h3>
{% else %}
<h3>Documentos citados</h3>
{% endif %}
<p>
	Total citas a artículos: {{total_articles}}</br>

<table class="table">
  <thead>
      <tr>
	        <th>Artículo</th>
	        <th>Documento</th>
	        <th>Citas</th>
	        <th>Percentage</th>
	  </tr>
  </thead>
  <tbody>
 	{% for (x,y),z in data.most_common(ntop) %}
		<tr><td class="has-text-right">{{y}}</td><td>{{x}}</td><td>{{z}}</td><td>{{"{0:.2%}".format(z/total_articles)}}</td></tr>
	{% endfor %}
  </tbody>
</table>


</p>
</div>

{% endblock %}

webapp/project/client/templates/main/cases_country.html
{% extends "_base.html" %}

{% block css %}
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
{% endblock %}


{% block content %}
<div class="content">

<h3>Casos por país</h3>
<p>
	Total de casos: {{total_cases}}

	<canvas id="histogram" width="400" height="400"></canvas>

	<script>
var ctx = document.getElementById("histogram");
var myChart = new Chart(ctx, {
    type: 'horizontalBar',
    data: {
        labels: [
		{% for x,y in data.most_common() %}
			"{{name_country[x]}}",
		{% endfor %}
		],
        datasets: [{
            data: [
			{% for x,y in data.most_common() %}
			"{{y}}",
			{% endfor %}
			],
			backgroundColor:[
			{% for x,y in data.most_common() %}
			"{{color_country[x]}}",
			{% endfor %}
			],
            borderWidth: 1
        }]
    },
    options: {
		legend: {
			            display: false
		},
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>


</p>
</div>

{% endblock %}

webapp/project/client/templates/main/country.html
{% extends "_base.html" %}

{% block css %}
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
{% endblock %}


{% block content %}
<div class="content">

<h3>{{title}}</h3>
<p>
	<canvas id="histogram" width="400" height="400"></canvas>

	<script>
var ctx = document.getElementById("histogram");
var myChart = new Chart(ctx, {
    type: 'horizontalBar',
    data: {
        labels: [
		{% for x in country_names %}
			"{{name_country[x]}}",
		{% endfor %}
		],
        datasets: [{
            data: [
			{% for x in country_names %}
			"{{data[x]}}",
			{% endfor %}
			],
			backgroundColor:[
			{% for x in country_names %}
			"{{color_country[x]}}",
			{% endfor %}
			],
            borderWidth: 1
        }]
    },
    options: {
		legend: {
			            display: false
		},
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>


</p>
</div>

{% endblock %}

webapp/project/client/templates/main/documents.html
<!--
 Penserbjorne - Sebastian Aguilar
 2017
 FI-IIMAS-IIJ-UNAM
-->

{% extends "_base.html" %}

{% block css %}
	<link rel="stylesheet" href="{{url_for('main.static', filename='gate.css')}}">
	<script type="text/javascript" src="{{url_for('main.static', filename='gate.js')}}"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
{% endblock %}


{% block content %}
<!-- Inicio pestañas -->
<div class="tabs is-centered" id="meTab">
  <ul>
    <li onclick="isActiveTab(this, tab0)" class="is-active"><a>Resumen</a></li>
    <li onclick="isActiveTab(this, tab1)"><a>Etiquetas</a></li>
    <li onclick="isActiveTab(this, tab2)"><a>Vocabulario</a></li>
    <li onclick="isActiveTab(this, tab3)"><a>Participantes</a></li>
    <li onclick="isActiveTab(this, tab5)"><a>Países</a></li>
    <li onclick="isActiveTab(this, tab6)"><a>Fechas</a></li>
  </ul>
</div>
<!-- Fin pestañas -->

<!-- Inicio Contenedores de las pestañas -->
  <!-- Resumen -->
  <div class="box" id="tab0">
    <strong>{{doc.meta_name.name}}</strong>
    <hr/>
    <div class="columns is-multiline">

      <div class="column is-2">
    	   <strong><em>Corte</em></strong>
      </div>
      <div class="column is-2">
    	   {{doc.meta_name.court}}
      </div>

      <div class="column is-2">
         <strong><em>Estructura</em></strong>
      </div>
      <div class="column is-6">
         {{doc.meta_name.actions}}
      </div>

      <div class="column is-2">
         <strong><em>Fecha</em></strong>
      </div>
      <div class="column is-2">
         {{doc.meta_name.date_sentence}}
      </div>

      <div class="column is-2">
    	   <strong><em>Número</em></strong>
      </div>
      <div class="column is-2">
    	   {{doc.meta_name.number}}
      </div>

      <div class="column is-2">
         <strong><em>Fuentes</em></strong>
      </div>
      <div class="column is-2">

        <a href="{{doc.source_pdf}}" arget="_blank">
          <span class="icon">
          <i class="fas fa-file-pdf"></i>
          </span>
        </a>

        <a href="{{doc.source_doc}}" arget="_blank">
          <span class="icon">
          <i class="fas fa-file-word"></i>
          </span>
        </a>

      </div>

    </div>

  </div>
  <!-- Inicio Seleccionar etiquetas -->
  <div class="box" id="tab1">

    <strong>Mostrar etiquetas</strong>
    <hr/>
    <div class="columns is-multiline">

      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxCaso" onclick="changeCSS('chkbxCaso','Case','nCase')">
          Caso
        </label>
      </div>

      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxMiembros" onclick="changeCSS('chkbxMiembros','PersonCourtMembers','nPersonCourtMembers')">
          Miembros de la corte
        </label>
      </div>

      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxFechas" onclick="changeCSS('chkbxFechas','Date2','nDate2')">
          Fechas
        </label>
      </div>

      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxArticulos" onclick="changeCSS('chkbxArticulos','ArticleMention','nArticleMention')">
          Artículos
        </label>
      </div>


      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxDocuments" onclick="changeCSS('chkbxDocuments','DocumentMention','nDocumentMention')">
          Documentos
        </label>
      </div>


      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxInstitutions" onclick="changeCSS('chkbxInstitutions','InstitutionMention','nInstitutionMention')">
          Instituciones
        </label>
      </div>

      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxDefinitions" onclick="changeCSS('chkbxDefinitions','Definition','nDefinition')">
    	  Definiciones
        </label>
      </div>


      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxPuntosResolutivos">
          Puntos resolutivos
        </label>
      </div>

      <div class="column">
        <label class="checkbox">
          <input type="checkbox" checked id="chkbxConectores">
          Conectores semánticos
        </label>
      </div>

    </div>

  </div>
  <!-- Fin Seleccionar etiquetas -->

  <!-- Vocabulario -->
  <div class="box" id="tab2">
    <strong>Vocabulario (top {{nvoc}})</strong>
    <hr/>

    <div class="columns">
      <div class="column">
        <table class="table is-narrow">
		<tbody>
		<tr>
        {% for par in fdist.most_common(nvoc) %}
			<td>
              <strong>{{par[0]}}</strong>, {{par[1]}}
			</td>
			{% if loop.index%4 == 0 %}
				</tr>
				<tr>
			{% endif %}
        {% endfor %}
		</tr>
		<tbody>
        </table>

      </div>
      <div class="column is-half has-text-centered">

	<canvas id="histogram" width="400" height="400"></canvas>

	<script>
var ctx = document.getElementById("histogram");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [
		{% for x,y in fdist.most_common(nwords) %}
			"{{x}}",
		{% endfor %}
		],
        datasets: [{
            label: '# of words',
            data: [
			{% for x,y in fdist.most_common(nwords) %}
			"{{y}}",
			{% endfor %}
			],
			backgroundColor: 'rgba(54, 162, 235, 1)',
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>



      </div>
    </div>

  </div>

  <!-- Participantes -->
  <div class="box" id="tab3">
    <strong>Participantes</strong> - Hay un total de <strong id="titleParticipantes"></strong> participantes.
    <hr/>
    <div id="divParticipantes"></div>
  </div>

  <!-- Leyes y artículos -->
  <div class="box" id="tab4">
    <strong>Leyes y artículos</strong> - Hay un total de <strong id="titleArticulos"></strong> elementos.
    <hr/>
    <div class="columns is-multiline" id="divArticulos"></div>
  </div>

  <!-- Países -->
  <div class="box" id="tab5">
    <strong>Países</strong> - Hay un total de <strong id="titlePaises"></strong> países.
    <hr/>
    <div class="columns is-multiline" id="divPaises"></div>
  </div>

  <!-- Fechas -->
  <div class="box" id="tab6">
    <strong>Fechas</strong> - Hay un total de <strong id="titleFechas"></strong> fechas.
    <hr/>
    <div id="divFechas"></div>
  </div>
<!-- Fin Contenedores de las pestañas -->


<div class="columns">
<div class="column is-four-fifths">
<div class="notification" onclick="something_click(event)">
	{% for line in xml %}{{line | safe }}</br>{% endfor %}
  <!-- <iframe id="documentFrame" width="100%" scrolling="auto" src="{{url_for('main.xml', filename=filename)}}"></iframe> -->
</div>
</div>
<div class="column">
<article class="message is-primary">
  <div class="message-header">
    <p>Info tag</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div id="info-tag"class="message-body">
  </div>
</article>	
</div>

</div>

<script src="{{url_for('main.static', filename='documents.js')}}" type="text/javascript"></script>

{% endblock %}

webapp/project/client/templates/main/documents_citation.html
{% extends "_base.html" %}

{% block content %}
<div class="content">

{% if ntop %}
<h3>{{ntop }} Documentos citados</h3>
{% else %}
<h3>Documentos citados</h3>
{% endif %}
<p>
	Total citas de documentos: {{total_cases}}</br>

<table class="table">
  <thead>
      <tr>
	        <th>Documento</th>
	        <th>Citas</th>
	        <th>Percentage</th>
	  </tr>
  </thead>
  <tbody>
 	{% for x,y in data.most_common(ntop) %}
		<tr><td>{{x}}</td><td>{{y}}</td><td>{{"{0:.2%}".format(y/total_cases)}}</td></tr>
	{% endfor %}
  </tbody>
</table>

</p>
</div>

{% endblock %}

webapp/project/client/templates/main/home.html
{% extends "_base.html" %}

{% block content %}

Este plataforma busca ...

{% endblock %}

webapp/project/client/templates/main/law.html
{% extends "_base.html" %}

{% block content %}


<div class="content">
<p>
<h3 class="title"><strong>{{doc.meta_name.name}}</strong></h3>
</p>
<hr/>
<div class="columns is-multiline">
  <div class="column is-2">
	<em>Título</em>
  </div>
  <div class="column is-10">
	{{doc.title}}
  </div>


  <div class="column is-2">
	<em>Número</em>
  </div>
  <div class="column is-10">
	{{doc.meta_name.number}}
  </div>

  <div class="column is-2">
	<em>Corte</em>
  </div>
  <div class="column is-10">
	{{doc.meta_name.court}}
  </div>

  <div class="column is-2">
	<em>Fecha</em>
  </div>
  <div class="column is-10">
	{{doc.meta_name.date_sentence}}
  </div>


  <div class="column is-2">
	<em>Visualizaciones</em>
  </div>
  <div class="column is-10">
    <a href="{{doc.source_pdf}}" arget="_blank" >
      <span class="icon">
          <i class="fas fa-file-pdf"></i>
      </span>
    </a>

    <a onclick="document.getElementById('docForm{{doc.eid}}').submit();">
      <span class="icon">
          <i class="fas fa-file-code"></i>
      </span>
    </a>

    <a onclick="document.getElementById('{{doc.meta_name.name}}').submit();">
      <span class="icon">
          <i class="fas fa-eye"></i>
      </span>
    </a>

    <form id="docForm{{doc.eid}}" method="GET" action="doc/">
      <input type="hidden" id="docXmlName" name="docXmlName" value="{{doc.txt.rsplit("/",1)[1]}}">
      <input type="hidden" id="docNum" name="docNum" value="{{doc.eid}}">
    </form>
    <form id="{{doc.meta_name.name}}" method="POST" action="graph/">
      <input type="hidden" id="include" name="include" value="{{doc.meta_name.name | lower}}">
    </form>
  </div>
</div>
</div>

{% endblock %}

webapp/project/client/templates/main/laws.html
{% extends "_base.html" %}

{% block content %}

<div class="content">
    <h3 class="title">Documentos</h3>

	<div class="field">
	    <div class="control">
			<input class="input is-primary" type="text" id="myFilterLaw" onkeyup="myFilterLaw()" placeholder="Palabras claves">
	   </div>
	</div>

	<table class="table" id='lawsTable'>
    <thead>
      <tr>
        <th width="60%">Caso</th>
        <th>Serie</th>
        <th>Fecha</th>
        <th>Ligas</th>
      </tr>
    </thead>
    <tbody>
	  {% for doc in docs %}
      <tr>
        <td><a href="{{url_for('main.law',idd=doc.eid)}}">{{doc.meta_name.name}}<a></td>
        <td>{{doc.meta_name.number}}</td>
        <td>{{doc.meta_name.date_sentence}}</td>
        <td>

  		<a href="{{doc.source_pdf}}" arget="_blank" >
  			<span class="icon">
          	<i class="fas fa-file-pdf"></i>
        </span>
  		</a>

      <a onclick="document.getElementById('docForm{{doc.eid}}').submit();">
  			<span class="icon">
			<i class="fas fa-file-code"></i>
        </span>
  		</a>

  		<a onclick="document.getElementById('{{doc.meta_name.name}}').submit();">
  			<span class="icon">
          	<i class="fas fa-eye"></i>
        </span>
  		</a>

      <form id="docForm{{doc.eid}}" method="GET" action="doc/">
        <input type="hidden" id="docXmlName" name="docXmlName" value="{{doc.txt.rsplit("/",1)[1]}}">
        <input type="hidden" id="docNum" name="docNum" value="{{doc.eid}}">
      </form>
      <form id="{{doc.meta_name.name}}" method="POST" action="graph/">
        <input type="hidden" id="include" name="include" value="{{doc.meta_name.name | lower}}">
  		</form>

		</td>
      </tr>
	 {% endfor %}
    </tbody>
  </table>
</form>
</div>


<script>
   function DoPost(page,params){
	   console.log(page,params);
	         $.post(page,params );
	}
</script>
{% endblock %}

webapp/project/client/templates/main/list_numbers.html
{% extends "_base.html" %}

{% block content %}

<div class="content">
<p>
<ul>
	<li><a href="{{url_for("main.cases_country")}}">Casos por país</li>
	<li><a href="{{url_for("main.documents_citation")}}">Documentos citados</li>
	<li><a href="{{url_for("main.articles_citation")}}">Artículos citados</li>
	<li><a href="{{url_for("main.numbers_arcs_country")}}">Citas normalizadas por país</li>
	<li><a href="{{url_for("main.numbers_adc_country")}}">Promedio grado de centralidad por país</li>
	<li><a href="{{url_for("main.numbers_density_country")}}">Densidad por país</li>
</ul>
</p>
</div>

{% endblock %}